id = "mach"
name = "Mach"
version = "0.5.0"
schema_version = 1
authors = ["octalide"]
description = "Mach language support for Zed — syntax highlighting, indentation, and LSP integration."
repository = "https://github.com/briar-systems/mach-zed"

[grammars.mach]
repository = "https://github.com/briar-systems/mach-tree-sitter"
rev = "f1972d35786055e48d512c7d66bed69d2de93ad6"

[language_servers.mls]
name = "Mach Language Server"
languages = ["Mach"]
